### ISSUE TITLE
Widget/Button/Link to trigger the Notification popup.

### ISSUE THREAD

**Issue by FrozenBeard** [OneSignal/OneSignal-WordPress-Plugin#105]
That big red button isn't very user friendly, design friendly, or fit in with any website design. 
Can we please have a simple way to put a button of our own design where we want to trigger the popup notification? or even just an onclick event so we can use our own code to trigger the popup notification without using the red alert icon!

For normal users a widget may be a much better premade solution, one that explains what that notification tab is.

**Comment by dpacmittal** [comment]
Second this. Need a manual way to trigger notification popup.

**Comment by jasonpang** [comment]
Hi @FrozenBeard @dpacmittal,

Because our WordPress plugin includes our web SDK which powers web push, prompting, and subscription, you may use any [public SDK JavaScript API](https://documentation.onesignal.com/docs/web-push-sdk) with your custom widget / button / link to trigger the notification popup.

Please review our documentation guides like [triggering prompts from JavaScript](https://documentation.onesignal.com/docs/permission-requests#section-onesignal-prompts)
 and [triggering the final browser permission request](https://documentation.onesignal.com/docs/web-push-custom-code-examples#section-permission-requests).

**Comment by Pd08111997** [comment]
From The Above Code, I and Getting A button That is not responsive and the size is out of screen resolution.
What I want to do is How can I connect this code to a button on my website that I have made from a drag and drop tool. Is this possible to connect this to a buy=toon that is already on my website or blog?

**Comment by Pd08111997** [comment]
Or How Can I make that button responsible to screen size?
