### ISSUE TITLE
The script has an unsupported MIME type application/octet-stream, Failed to register/update a ServiceWorker

### ISSUE THREAD

**Issue by kaziqta** [OneSignal/OneSignal-WordPress-Plugin#107]
ringing on the bell gives me that:
Failed to register/update a ServiceWorker for scope ‘https://vulkk.com/’: Bad Content-Type of ‘application/octet-stream’ received for script ‘https://vulkk.com/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/OneSignalSDKWorker.js.php?appId=1df09024-f601-4629-8cb1-93e4b37dab7c’.  Must be ‘text/javascript’, ‘application/x-javascript’, or ‘application/javascript’.

I am using nginx and I can set the Mime type:

text/javascript php; # you can understand that is completely wrong, but it works.

after that I get (fixing the mime):
 Failed to register a ServiceWorker: The path of the provided scope ‘https://vulkk.com/’ is not under the max scope allowed ‘https://vulkk.com/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/’. Adjust the scope, move the Service Worker script, or use the Service-Worker-Allowed HTTP header to allow the scope.

Please advise

**Comment by fatsjohonimahnn** [comment]
You will need to contact nginx and ask them to serve these 3 files as application/javascript:

https://vulkk.com/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/OneSignalSDKWorker.js.php

https://vulkk.com/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/OneSignalSDKUpdaterWorker.js.php

https://vulkk.com/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/manifest.json.php

Feel free to contact support@onesignal.com and provide your app ID and the add the plugin back to your site to get further assistance.

**Comment by jasonpang** [comment]
Hi @kaziqta,

If you discover why the PHP scripts weren't executing as PHP, we'd be interested in learning why. Feel free to leave a comment here.

We're closing this issue because this is most likely a server configuration issue and isn't a bug with our WordPress plugin.

**Comment by kaziqta** [comment]
yeah, I understand, the thing is I cannot find a way to make it by setting it, I understand you are not into the backend :) ok, if I find out why, I will report it, it may happen with other people too, I have already had 2 servers, that don't take it :) good luck for now

**Comment by kaziqta** [comment]
alright, what about the second console error after I fix the mime:

```
location ~ [^/]\js.php(/|$) {
                 default_type application/x-javascript;
        }
```

Failed to register a ServiceWorker: The path of the provided scope ‘https://vulkk.com/’ is not under the max scope allowed ‘https://vulkk.com/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/’. Adjust the scope, move the Service Worker script, or use the Service-Worker-Allowed HTTP header to allow the scope.

**Comment by jasonpang** [comment]
Hey @kaziqta,

Forcing the MIME type is just a band-aid that doesn't execute the actual worker PHP script.

Once these script files run their PHP code, you will no longer receive these errors, because these script files set the correct MIME type and add the appropriate headers using PHP code.

Can you investigate why these files aren't executing as PHP scripts?

**Comment by Lofesa** [comment]
Hi @jasonpang 
I found the reason (al most in nginx server) because these files are not executed.
The cause is the .json.php or .js.php in the files naming.
The test I have done in chrome browser:
https://mydomain.com/....../manifest.json.php  vs. https://mydomain.com/..../manifest.php
The first one download the file as it, the second return the json content and have the application/json header set.

I have tried to ceate a nginx location like the one I use for php files

```
location ~ \.json\.php {
        fastcgi_split_path_info ^(.+?\.json\.php)(/.*)$;
         try_files $uri $uri/ /index.php$is_args$args;
         include default.d/fastphp.conf;
}
```
but no luck, the file still not be executed, only downloaded.

Is perhaps a nginx limitation? Nginx get the file extension only in the first dot? I don´t know, but it file os named manifest.php it work.

**Comment by Lofesa** [comment]
Hi @jackgregory 
I have used the code snipet in the above post, but they be before the php location, like this:

```
location ~* \.(js|json)\.php(/|$) {
        fastcgi_split_path_info ^(.+?\.json\.php)(/.*)$;
        fastcgi_split_path_info ^(.+?\.js\.php)(/.*)$;
        #try_files $uri $uri/ =404;
        try_files $uri $uri/ /index.php$is_args$args;
        # This is a robust solution for path info security issue and works with "cgi.fix_pathinfo = 1" in /etc/php.ini (default)
        #
        include default.d/fastphp.conf;

}

location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        try_files $uri $uri/ /index.php$is_args$args ;
        # This is a robust solution for path info security issue and works with "cgi.fix_pathinfo = 1" in /etc/php.ini (default)
        #
        include default.d/fastphp.conf;

}

```

**Comment by uded** [comment]
It seems that the most obvious, simple, and the commonly correct solution would be to rename those `*.js.php` files to just `*.php` and the problem would be gone. We had to change our config as well, and that is completely pointless...

I vote to reopen this issue, change the extension of those files and the problem will be gone. Or find a better solution. Because on the servers with a bit tighter config, this will happen often...
