### ISSUE TITLE
GDPR and Cookie Law

### ISSUE THREAD

**Issue by stefa98** [OneSignal/OneSignal-WordPress-Plugin#132]
Hi, I would like to know where I can find the initial OneSignal in the plugin files in order to insert preventive cookie blocking codes. Here is an example below:

<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async></script>
<script>
var OneSignal = window.OneSignal || [];
OneSignal.push(["init", {
  appId: "id",
  autoRegister: false,
  notifyButton: {
    enable: false /* Set to false to hide */
  }
}]);
</script>

**Comment by jkasten2** [comment]
@stefa98 You will need to first disable automatic init the OneSignal WordPress does. 

1. At the bottom of the OneSignal WordPress settings you will need to toggle on "Disable OneSignal initialization".

![image](https://user-images.githubusercontent.com/645861/40521376-244a6a8a-5f80-11e8-9ab9-73eb786f0687.png)

2. Then you can initialize OneSignal through javascript with the `requiresUserPrivacyConsent` setting.

```html
<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async></script>
<script>
  var OneSignal = window.OneSignal || [];
  window._oneSignalInitOptions["requiresUserPrivacyConsent"] = true;
  OneSignal.push(["init", window._oneSignalInitOptions]);
</script>
```
`window._oneSignalInitOptions` contains all the settings from the WordPress plugin all parameters  including app_id are already set in here.

3. When the user accepts your privacy agreement you will need to call `userTappedProvideConsentButton`
```javascript
function userTappedProvideConsentButton() {
  // Will initialize the SDK and register for push notifications
  OneSignal.push(function() {
    OneSignal.provideUserConsent(true);
  });
}
```

**Comment by rklf** [comment]
Hello,
I contact you about Wordpress plugin. When I enable "Disable OneSignal initialization" in Advanced settings, it seems like it still initializes.
Furthermore, when I add the script manually to my "functions.php" child. I get the following error when I check Chrome's Dev console :
- windows.OneSignal already defined as 'object' 

I guess it's because OneSignal is initialized twice because the wordpress plugin doesn't disable the initialization. Any idea ?
