### ISSUE TITLE
Improve ease-of-use for importing additional service workers

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-WordPress-Plugin#26]
Add a custom textbox to the admin panel for 3rd party service workers and call importScripts() in OneSignalSDKWorker.js.php and OneSignalSDKUpdaterWorker.js.php for each URL.

**Comment by jasonpang** [comment]
More research needed to figure out how to do this [without including wp-load.php](http://ottopress.com/2010/dont-include-wp-load-please/) to get a WordPress setting and without unsafely passing a parameter to the script to be imported.

**Comment by jasonpang** [comment]
Although there isn't a shiny UI for this feature, users can still manually edit the `OneSignalSDKWorker.js.php` and `OneSignalSDKUpdaterWorker.js.php` files to include their additional service worker. This is how non-WordPress users using our SDK are including their service workers and it shouldn't be a big deal since this change will presumably be made only once.

**Comment by arunbasillal** [comment]
Hey @jasonpang 

I am trying to do this, and manually editing `OneSignalSDKWorker.js.php` and `OneSignalSDKWorker.js.php` seems to be the only solution as you said above. 

However, in the WordPress context, these files are replaced with every WordPress update and any manual edits will be lost. 

Is there a better way to do this? 

A solution: 

- Generate these files during plugin activation (and regenerate them during updates if changes are needed). 
- Include a WordPress action hook where other developers can add their `importScripts` to. 
- The location of `OneSignalSDKWorker.js.php` and `OneSignalSDKWorker.js.php` will have to be changed to the root folder or somewhere outside the plugins folder so that it is not overwritten with each update. 

Please let me know if there is another way to do this. Also, if my solution is something that sounds even remotely good, I would love to code that part and send a PR to your team. 

Best regards.

**Comment by gdeglin** [comment]
@arunbasillal 

Thanks for the suggested solutions and offering to work on this! The action hook method is probably the best approach. The other two approaches require writing/editing files on the server and our experience has been that some webhosts and wordpress configurations prevent plugins from being able to do this.

We'd love to look at a PR for this. It may take us a little white to review the PR though since our team is quite busy.

**Comment by Timbral** [comment]
Any progress on this exposing an action hook?
