### ISSUE TITLE
Plugin Admin-UI has so much asset files

### ISSUE THREAD

**Issue by TahiriAbdou** [OneSignal/OneSignal-WordPress-Plugin#74]
the admin dashboard has so many assets including jquery.js / bootstrap.js / semantic.js , and css files (around 1.2mb of css), is it possible to optimize admin dashboard on future versions  ?

**Comment by jasonpang** [comment]
Hey @TahiriAbdou,

We'll take a look at this for our next WordPress plugin and optimize what we can.

**Comment by jasonpang** [comment]
Hey @TahiriAbdou,

Thanks for contributing! It looks like `bootstrap.min.css` and `bootstrap.min.js` were never used, so it was a mistake to have included these in the first place. It looks like the other styles are being used though.

I think these styles and scripts are only loaded when you click our *OneSignal Push* menu entry in your WordPress admin dashboard. The styles and scripts should not be loaded in our admin pages (as far as I know) and certainly not on your main site. So you should only have run into minimal performance issues by the additional unused bootstrap JS/CSS.

The pull request you submitted removes files that are used like semantic-ui.css (we use Semantic UI instead of Bootstrap), so I hope you don't mind if I close it!

Fixed by: https://github.com/OneSignal/OneSignal-WordPress-Plugin/commit/8c4430d4c9409f57b6d5677696b1cf87481e22a8

**Comment by TahiriAbdou** [comment]
Hey @jasonpang ,

i took a deep look to the plugin files, and  in my pull request I removed the unused files such ```bootstrap.min.css```and ```bootstrap.min.js```, but i didn't remove the others.

Instead if you made a review of my pull request, i was tending to minify the other css files used by the plugin. the original files were around 1.5mb of css files which is not good considering the purpose of plugin .

So i suggest to take a deep look into this subject .

**Comment by jasonpang** [comment]
Hey @TahiriAbdou,

You're right, sorry about that! After clicking `Show diff`, it looks like you were just minifying the files to make the smaller. Sorry I missed that. I looked at this quickly so I thought the files were being deleted.

Your changes will be out in the next plugin release. Thanks again for contributing!
