### ISSUE TITLE
Push notification not working Safari 10.0.2/MacOS 10.12.2

### ISSUE THREAD

**Issue by idarek** [OneSignal/OneSignal-WordPress-Plugin#76]
I have added OneSignal via plugin to two Wordpress sites
https://www.paraplan.com.pl
and
https://www.andrewsfasteners.uk

Push notification seams to work ok in Chrome on macOS, but not in Safari.

1. On Chrome, even that got set in settings to ask new visitors for notifications, no pop-up appear and need to hit the bell icon to get request for it.
2. On Safari not working in both cases. Not even when hit on bell icon - nothing happens. Sometimes bell icon is associated with black dot.

Tried clean cache, remove notification settings etc, nothing help.
Check on other mac with same results.

Don't see any strange errors in console. Sites are working over cloudflare and rocket is turn off there just in case.

**Comment by jasonpang** [comment]
Hi @idarek,

In the future, could you please ask WordPress plugin related setup issues in our OneSignal chat support if you're not completely sure it's a plugin bug? Because our plugin is made up of different components like our web SDK and our backend delivery service, issues you experience may be caused by any one of these components and may not necessarily be a plugin bug. Our chat support also helps us organize our conversations and it makes it easier to review past conversations with people. We should also get back to you faster on our chat support.

For the two sites you've linked, Could you please try uploading a Safari icon into each of the upload textboxes shown here: https://i.imgur.com/iuhAP8w.png? We've figured out what causes this issue for Safari sites and new apps created since a few weeks ago should no longer have this issue. Apps created older than a few weeks ago have this issue.
