### ISSUE TITLE
Add filter hook for getting OneSignal settings

### ISSUE THREAD

**Issue by AaronHolbrook** [OneSignal/OneSignal-WordPress-Plugin#88]
Right now only storing the keys in the database presents a serious problem: accidental push notifications on test/dev environments.

Use case:
```
* Set up plugin on production, set secret key appropriately for production usage
* Clone production database to stage, local, etc
* Create test post, user can submit posts to 'prod' audience (intentionally or unintentionally)
```

There are a few ways to fix/prevent this from happening. The simplest would be to check for PHP constants and use those if they exist, otherwise attempt to use the ones in the DB/prompt for those.

This allows us to define configurations at an environmental level and not require access keys be stored in the database.

Thanks!

**Comment by AaronHolbrook** [comment]
Additionally, a simple filter on `get_onesignal_settings` would also work, as it stands right now, there's no way to intercept these calls to the db/prevent accidental notifications from non-prod environments.

**Comment by jasonpang** [comment]
Hey @AaronHolbrook,

A `get_onesignal_settings` filter sounds doable. In the above described use case, cloning the production database to staging/local sounds like it would invite issues, so I want to say this cloning is the real issue here. Since developers have different ways of integrating/testing our WordPress plugin, the filter hook sounds like a good way to support these different cases generally. We'll try to add it in a future update!

**Comment by AaronHolbrook** [comment]
Unfortunately, sometimes this is the setup that we're faced with and we have to make do, however I always try to ensure that nothing from development should ever be executing something that can cause anything from production to occur (i.e. sending mass emails to customers, tweeting on the live production account, sending notifications etc).

These things should be overrideable and manageable by the codebase hence preventing any mishaps; a filter would be greatly appreciated!

Thanks @jasonpang !

**Comment by AaronHolbrook** [comment]
Any hope in getting this PR for the filter merged?
