### ISSUE TITLE
DOMException: Registration failed - push service error

### ISSUE THREAD

**Issue by rajasajidmanzoor** [OneSignal/OneSignal-WordPress-Plugin#96]
Hello,

I am using One Signal WP plugin in one of my project www.newslume.com
I am having following error
` OneSignal SDK Uncaught (in promise) DOMException: Registration failed - push service error `

This error is shown in console, if a user clicks allow button for first time.

![image](https://user-images.githubusercontent.com/5917783/29762046-c489d02c-8be5-11e7-8b06-4cac3f2b496d.png)

If i visit website next time, it is showing following error in console.

![image](https://user-images.githubusercontent.com/5917783/29762076-eb8f0bd8-8be5-11e7-9ed2-7f9f01aec27a.png)

Plz check and confirm, where i am doing wrong.

**Comment by jasonpang** [comment]
Can you visit the URL `chrome://gcm-internals` on your browser and post a screenshot like the one below?

![image](https://user-images.githubusercontent.com/1015970/29762132-ad5af14c-8b81-11e7-9fa1-54946e05cf9c.png)

Which Chrome version are you using and what operating system are you on?

**Comment by rajasajidmanzoor** [comment]
Here it is

![image](https://user-images.githubusercontent.com/5917783/29762614-c5a9d8a0-8be8-11e7-83f7-c0f11af5ac82.png)

Chrome Version
![image](https://user-images.githubusercontent.com/5917783/29762632-e6ca8fb6-8be8-11e7-811d-00e445f48889.png)

OS: Windows 7 and Windows 10 ( have issues on both)

I also tested on Opera i have same issues with opera as well.

![image](https://user-images.githubusercontent.com/5917783/29762641-03b4155c-8be9-11e7-9462-62d0497f91ee.png)

**Comment by jasonpang** [comment]
- Were you able to subscribe for web push successfully before? Did this issue start happening recently? Your screenshot shows VAPID subscriptions for http://localhost, https://gauntface.github.io, https://hostinpakistan.os.tc, and https://newslume.com, in the "Registered App Ids" section.
  - Close all browser tabs and restart Chrome and visit chrome://serviceworker-internals. Do you have an entry for `Scope: https://newslume.com`?

    ![image](https://user-images.githubusercontent.com/1015970/29763838-a65dc1d2-8b89-11e7-9e92-635c6d490e6c.png)


- Do you receive the same error when trying out [Gauntface's simple push demo](https://gauntface.github.io/simple-push-demo/)? 



- Does your network environment block outgoing connections? Does running `curl -X POST https://android.clients.google.com/c2dm/register3` (Git Bash has `curl`) return any kind of network error?

**Comment by rajasajidmanzoor** [comment]
This is the result of chrome://serviceworker-internals

![image](https://user-images.githubusercontent.com/5917783/29764201-aa879d9e-8bef-11e7-8a06-2d9c8eba3354.png)

No error received while using Gauntface's simple push demo. see below screenshot

![image](https://user-images.githubusercontent.com/5917783/29764229-caf78de6-8bef-11e7-9f36-a0de3332b0ef.png)

This is result for  curl -X POST https://android.clients.google.com/c2dm/register3

![image](https://user-images.githubusercontent.com/5917783/29764299-05f63b18-8bf0-11e7-8ee9-85a674c0e1a1.png)

**Comment by tudormunteanu** [comment]
I'm starting to see this since a few days on Android Chrome too. Any updates on what might be the cause?

**Comment by jasonpang** [comment]
A few ways the `DOMException: Registration failed - push service error ` can occur are:

- The browser has partially implemented web push APIs but does not fully support web push (e.g. [< Opera v42](https://blogs.opera.com/desktop/changelog-for-42/#b2372.0), Chromium instead of Google Chrome)
- The `manifest.json` for subscribing to push contains an invalid `gcm_sender_id`

#### Browser Test

Try subscribing to web push on [this push demo](https://gauntface.github.io/simple-push-demo) and check if a push service error appears. If it does, your browser does not support web push.

#### `manifest.json` Test

Please use Chrome DevTools to search for occurences of `manifest`:

![image](https://user-images.githubusercontent.com/1015970/36176894-eec4dc7a-10c8-11e8-9202-55bceb48e220.png)

If there are multiple lines beginning with `<link rel="manifest" href="...">`, find the first result. The browser will use the first manifest it finds:

> In cases where more than one link element with a manifest link type appears in a Document, the user agent uses the first link element in tree order and ignores all subsequent link element with a manifest link type (even if the first element was erroneous). ([source](https://www.w3.org/TR/appmanifest/#x6-1-linking-to-a-manifest))

Check that the `gcm_sender_id` in the first manifest's contents exists and is a number around 7 - 15 digits or so. Specifically, `gcm_sender_id` _should not_ have any letters, words, or dashes.

As VAPID overtakes the `gcm_sender_id` method of subscribing, this error should appear less frequently.

**Comment by liamka** [comment]
i have same issue
but it worked before

<img width="709" alt="Снимок экрана 2020-12-11 в 3 30 13" src="https://user-images.githubusercontent.com/11809/101846069-3743f880-3b61-11eb-8c47-330f9066758b.png">

**Comment by tf0054** [comment]
I was suffered the issue (Registration failed) on my tablet and am guessing the tablet might be a cause of issue because mine is Huawei MatePad11 which doesnt have google play store.
